stacks:
  dotnet:
    webapi:
      name: Amido.Stacks.Templates
      type: nuget
      id: stacks-dotnet
    cqrs:
      name: Amido.Stacks.CQRS.Templates
      type: nuget
      id: stacks-dotnet-cqrs
  java:
    webapi:
      name: https://github.com/amido/stacks-java
      version: master
    cqrs:
      name: https://github.com/amido/stacks-java-cqrs
      version: main
    events:
      name: https://github.com/amido/stacks-java-cqrs-events
      version: main
  nodejs:
    csr: 
      name: https://github.com/amido/stacks-typescript-csr
      version: master
    ssr:
      name: https://github.com/amido/stacks-typescript-ssr
      version: master
  infra:
    aks: 
      name: https://github.com/amido/stacks-infrastructure-aks/
      version: master